services:
  - type: web
    name: chat-application
    env: node
    buildCommand: "npm install && npm install --prefix backend && npm install --prefix frontend && npx vite build --prefix frontend"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production